name: "Release storybook"

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      # Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.9"
          channel: "stable"

      - name: Download dependencies
        run: flutter clean && flutter pub get

      - name: Test package
        run: flutter test

  storybook:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      # Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.9"
          channel: "stable"

      - name: Build storybook
        working-directory: ./storybook
        run: |
          flutter pub get
          flutter build web --release

      # Disribute to Firebase
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_CI_SERVICE_ACCOUNT }}"
          target: "ardrive-ui"
          channelId: live
